@startuml

title __MODEL's Class Diagram__\n

  package  {
    package com.example.applicationsmanagement {
      package com.example.applicationsmanagement.model {
        class Application {
            - id : int
            - name : String
            - technologies : String
            - version : String
            - image_url : String
            - users : Set<User>
            + Application()
            + Application()
            + Application()
            + Application()
            + Application()
            + getId()
            + getName()
            + setName()
            + getUsers()
            + setUsers()
            + getVersion()
            + setVersion()
            + getTechnologies()
            + setTechnologies()
            + setId()
            + addUser()
            + equals()
            + hashCode()
            + getImage_url()
            + setImage_url()
            + toString()
        }
      }
    }
  }
  

  package  {
    package com.example.applicationsmanagement {
      package com.example.applicationsmanagement.model {
        class User {
            - id : int
            - name : String
            - username : String
            - password : String
            - image_url : String
            - apps : Set<Application>
            + User()
            + User()
            + User()
            + getId()
            + getName()
            + setName()
            + getApps()
            + setApps()
            + getUsername()
            + setUsername()
            + getPassword()
            + setPassword()
            + setId()
            + addApplication()
            + equals()
            + hashCode()
            + getImage_url()
            + setImage_url()
            + toString()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
