@startuml

title __APPLICATIONSMANAGEMENT's Class Diagram__\n

  package  {
    package com.example.applicationsmanagement {
      class AppServiceTests {
          + setUp()
          + testFindByIdWhenAppExists()
          + testFindByIdWhenAppDoesntExists()
          + testGetAppById()
          + testSave()
          + testUpdateSuccesful()
          + testAddUser()
          + testDeleteById()
          + testDeleteUserFromApp()
          + testGetAll()
          + testComputeUsers()
      }
    }
  }
  

  package  {
    package com.example.applicationsmanagement {
      class UserServiceTests {
          + setUp()
          + testFindByIdWhenUserExists()
          + testFindByIdWhenUserDoesntExists()
          + testGetUserById()
          + testSaveUser()
          + testUpdateSuccesful()
          + testAddApp()
          + testDeleteById()
          + testDeleteAppFromUser()
          + testGetAll()
          + testComputeUsers()
      }
    }
  }
  

  AppServiceTests o-- AppDaoInterface : appDao
  AppServiceTests o-- UserDaoInterface : userDao
  AppServiceTests o-- ModelViewMapper : mapper
  AppServiceTests o-- AppService : appService
  AppServiceTests o-- Application : app
  AppServiceTests o-- AppViewModel : appView
  UserServiceTests o-- AppDaoInterface : appDao
  UserServiceTests o-- UserDaoInterface : userDao
  UserServiceTests o-- ModelViewMapper : mapper
  UserServiceTests o-- UserService : userService
  UserServiceTests o-- User : user
  UserServiceTests o-- UserViewModel : userView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
